# _config.yml 文件修改后的内容

name: "ZHAO MINGHONG"  # 你的名字
title: "Student"  # 你的职位或角色
description: "Lingnan University Student"  # 个人简介
email: "ming13288075992@gmail.com"  # 你的电子邮件

# 社交媒体链接
social:
  twitter: "https://twitter.com/WatonBTC"  # 你的 Twitter 链接

# 其他配置可以保留不变，除非你想进一步修改
theme: jekyll-theme-minimal-resume
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://your-username.github.io" # the base hostname & protocol for your site

# 其他默认设置
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "/page:num"
jekyll-paginate: true
