name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # 使用 Ruby 3.0 或以上版本

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # 运行 bundle install 安装依赖

      - name: Build the Jekyll site
        run: bundle exec jekyll build  # 运行 Jekyll 构建

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # 使用 peaceiris 的 GitHub Pages 部署 action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Jekyll 构建输出的目录
